package com.example.engine

import android.content.Context
import android.util.Log
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.Response
import org.json.JSONObject
import java.io.BufferedOutputStream
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.FileWriter
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class DevEngine(private val context: Context) {

    private val client = OkHttpClient()

    // Base storage folder that works safely on all Android versions
    val devFolder: File
        get() = File(context.getExternalFilesDir(null), "MYRA_Dev_Files").apply {
            if (!exists()) mkdirs()
        }

    fun generateCodeAndSave(language: String, promptText: String, codeSnippet: String): FileResult {
        return try {
            val extension = when (language.lowercase()) {
                "kotlin", "kt" -> "kt"
                "java" -> "java"
                "html" -> "html"
                "css" -> "css"
                "javascript", "js" -> "js"
                "python", "py" -> "py"
                "xml" -> "xml"
                "json" -> "json"
                else -> "txt"
            }
            val fileName = "myra_code_${System.currentTimeMillis()}.$extension"
            val file = File(devFolder, fileName)
            FileWriter(file).use { writer ->
                writer.write("// Generated by MYRA v2 — Ultimate AI Companion\n")
                writer.write("// Language: $language\n")
                writer.write("// Prompt: $promptText\n\n")
                writer.write(codeSnippet)
            }
            FileResult.Success(file, "Code file created: ${file.absolutePath}")
        } catch (e: Exception) {
            Log.e("DevEngine", "Error generating code", e)
            FileResult.Error(e.message ?: "Failed to generate and save code snippet")
        }
    }

    fun buildWebProject(projectName: String, html: String, css: String, js: String): ProjectResult {
        return try {
            val projectDir = File(devFolder, projectName.ifEmpty { "project_${System.currentTimeMillis()}" }).apply {
                if (!exists()) mkdirs()
            }

            // Create files
            val htmlFile = File(projectDir, "index.html").apply { rewrite(html) }
            val cssFile = File(projectDir, "style.css").apply { rewrite(css) }
            val jsFile = File(projectDir, "script.js").apply { rewrite(js) }

            // Create ZIP
            val zipFile = File(devFolder, "${projectDir.name}.zip")
            zipDirectory(projectDir, zipFile)

            ProjectResult.Success(projectDir, zipFile, "Project '${projectDir.name}' created inside MYRA_Dev_Files! HTML, CSS, and JS structures have been fully zipped.")
        } catch (e: Exception) {
            Log.e("DevEngine", "Error building web project", e)
            ProjectResult.Error(e.message ?: "Failed to assemble web files")
        }
    }

    suspend fun deployToService(zipFile: File, netlifyToken: String?): DeploymentResult {
        if (netlifyToken.isNullOrBlank()) {
            // Simulated / Mock ultra-cool deployment
            val randomSubdomain = "myra-${zipFile.nameWithoutExtension.lowercase().replace(Regex("[^a-z0-9]"), "")}-${(1000..9999).random()}"
            val mockUrl = "https://$randomSubdomain.netlify.app"
            return DeploymentResult.Success(
                url = mockUrl,
                status = "Deployed (Simulation Offline Mode)",
                message = "Netlify deployment simulated! Setup a Netlify API token in settings for direct online hosting."
            )
        }

        return try {
            // Real Netlify REST deployment
            // Step 1: Create a site or deploy to a default one. To deploy a zip, 
            // Netlify allows calling POST https://api.netlify.com/api/v1/sites with the raw zip bytes!
            val request = Request.Builder()
                .url("https://api.netlify.com/api/v1/sites")
                .header("Authorization", "Bearer $netlifyToken")
                .post(zipFile.asRequestBody("application/zip".toMediaType()))
                .build()

            val response: Response = client.newCall(request).execute()
            if (response.isSuccessful) {
                val json = JSONObject(response.body?.string() ?: "{}")
                val url = json.optString("ssl_url").ifEmpty { json.optString("url") }
                DeploymentResult.Success(url, "Live on Netlify", "Deployment complete! Your project was uploaded successfully via MYRA.")
            } else {
                val errBody = response.body?.string() ?: "Unknown Netlify API response"
                DeploymentResult.Error("Netlify responded with code ${response.code}: $errBody")
            }
        } catch (e: Exception) {
            Log.e("DevEngine", "Hosting deployment failed", e)
            DeploymentResult.Error("Netlify server connection failure: ${e.message}")
        }
    }

    private fun File.rewrite(content: String) {
        FileWriter(this).use { it.write(content) }
    }

    private fun zipDirectory(dir: File, zipFile: File) {
        ZipOutputStream(BufferedOutputStream(FileOutputStream(zipFile))).use { zos ->
            val files = dir.listFiles() ?: emptyArray()
            val buffer = ByteArray(4096)
            for (file in files) {
                if (file.isDirectory) continue // simple flat layout for web
                val entry = ZipEntry(file.name)
                zos.putNextEntry(entry)
                FileInputStream(file).use { fis ->
                    var count: Int
                    while (fis.read(buffer).also { count = it } != -1) {
                        zos.write(buffer, 0, count)
                    }
                }
                zos.closeEntry()
            }
        }
    }

    sealed class FileResult {
        data class Success(val file: File, val message: String) : FileResult()
        data class Error(val error: String) : FileResult()
    }

    sealed class ProjectResult {
        data class Success(val folder: File, val zipFile: File, val message: String) : ProjectResult()
        data class Error(val error: String) : ProjectResult()
    }

    sealed class DeploymentResult {
        data class Success(val url: String, val status: String, val message: String) : DeploymentResult()
        data class Error(val error: String) : DeploymentResult()
    }
}
